### Day 13
#### part A

In [1]:
import numpy as np

In [2]:
infile="13a_input.txt"

In [3]:
with open(infile) as f:
    start=int(f.readline().replace("\n",""))
    idslist=f.readline().replace("\n","")

In [4]:
idslist=idslist.split(",")
ids=[int(i) for i in idslist if i!="x"]

In [5]:
ids

[13, 37, 449, 29, 19, 23, 773, 41, 17]

In [6]:
start

1002576

In [7]:
for i in ids:
    mod=start%i
    if mod==0:
        wait=0
    else:
        wait=i-mod
    print("id",i,"waiting:",wait)

id 13 waiting: 10
id 37 waiting: 13
id 449 waiting: 41
id 29 waiting: 12
id 19 waiting: 16
id 23 waiting: 17
id 773 waiting: 5
id 41 waiting: 38
id 17 waiting: 16


In [8]:
# earliest bus is id 773 with waiting time 5
773*5

3865

#### part B

In [15]:
delays=[]
for idx,val in enumerate(idslist):
    if val!="x":
        delays.append(idx)
print("ID,    delay")
for tmpid,tmpdelay in zip(ids,delays):
    print(tmpid,",  ",tmpdelay)

ID,    delay
13 ,   0
37 ,   7
449 ,   13
29 ,   15
19 ,   32
23 ,   36
773 ,   44
41 ,   54
17 ,   61


#### equations
1. $13*n1=t$
2. $37*n2=t+7$
3. $449*n3=t+13$
4. $29*n4=t+15$
5. $19*n5=t+32$
6. $23*n6=t+36$
7. $773*n7=t+44$
8. $41*n8=t+54$
9. $17*n9=t+61$

#### observations
* n7 is multiple of 37 (see n2 and n7 line: $773*n7=t+7+37=37*(n2+1)$). with m7=n7/37: ```(773*37)*m7=t+44```
* n3 is multiple of 13 (see n1 and n3 line). with m3=n3/13: ```(449*13)*m3=t+13```
* -> ```m3=[(773*37)*m7-44+13]/(449*13)```
* all numbers on the left side of the equations are prime.

#### continuing the argumentation similarly:
* ```7. 773*n7=t+44```
    * 2.: n7 is multiple of 37
    * 4.: n7 is multiple of 29
    * 9.: n7 is multiple of 17
    * $-> \mathbf{(773*37*29*17)*a=t+44}$

* ```3. 449*n3=t+13```
    * 1.: n3 is multiple of 13
    * 5.: n3 is multiple of 19
    * 6.: n3 is multiple of 23
    * 8.: n3 is multiple of 41
    * $-> \mathbf{(449*13*19*23*41)*b=t+13}$

* $\mathbf{a,b, \in N}$

#### solving for b:
$\mathbf{b = [(773*37*29*17)*a-44+13] / (449*13*19*23*41)}$

In [56]:
%%time
# try integer values for a and check whether b is then also an integer
#for a in range(100000):
a=0
while True:
    remainder=((773*37*29*17)*a-44+13) % (449*13*19*23*41)
    if a%1000000==0:
        t=(773*37*29*17)*a-44
        print("Iteration",a, "t:",t)
        #pass
    if remainder==0:
        t=(773*37*29*17)*a-44
        print("a:",a, "t:",t)
        break
    a+=1
print("done")

Iteration 0 t: -44
Iteration 1000000 t: 14100292999956
Iteration 2000000 t: 28200585999956
Iteration 3000000 t: 42300878999956
Iteration 4000000 t: 56401171999956
Iteration 5000000 t: 70501464999956
Iteration 6000000 t: 84601757999956
Iteration 7000000 t: 98702050999956
Iteration 8000000 t: 112802343999956
Iteration 9000000 t: 126902636999956
Iteration 10000000 t: 141002929999956
Iteration 11000000 t: 155103222999956
Iteration 12000000 t: 169203515999956
Iteration 13000000 t: 183303808999956
Iteration 14000000 t: 197404101999956
Iteration 15000000 t: 211504394999956
Iteration 16000000 t: 225604687999956
Iteration 17000000 t: 239704980999956
Iteration 18000000 t: 253805273999956
Iteration 19000000 t: 267905566999956
Iteration 20000000 t: 282005859999956
Iteration 21000000 t: 296106152999956
Iteration 22000000 t: 310206445999956
Iteration 23000000 t: 324306738999956
Iteration 24000000 t: 338407031999956
Iteration 25000000 t: 352507324999956
Iteration 26000000 t: 366607617999956
Iteration